version: '3.0'
services:
  db:
    image: postgres:13.3
    container_name: archangel_db
    command: postgres -c listen_addresses='*'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.0
    container_name: archangel_redis
    restart: always
    ports:
      - '6379'
    volumes:
      - ./tmp/redis/redis.conf:/usr/local/etc/redis/redis.conf
  sidekiq:
    build: .
    container_name: archangel_sidekiq
    command: bash -c 'rm -f tmp/pids/sidekiq.pid && bundle exec sidekiq'
    restart: always
    environment:
      JOB_QUEUE_ADAPTER: sidekiq
      NODE_ENV: development
      RAILS_ENV: development
      REDIS_PROVIDER: redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/archangel
  app:
    build: .
    container_name: archangel_app
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
      - '3035:3035'
    environment:
      DB_HOST: db
      DB_PASSWORD: password
      JOB_QUEUE_ADAPTER: sidekiq
      NODE_ENV: development
      RAILS_ENV: development
      REDIS_PROVIDER: redis:6379
    depends_on:
      - db
      - redis
      - sidekiq
    volumes:
      - .:/var/www/archangel
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: archangel_web
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./public:/var/www/archangel/public
      - ./log:/var/www/archangel/log
volumes:
  postgres:
