# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  url: <%= ENV.fetch('DB_URL', '') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'archangel_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'archangel_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'archangel_production') %>
